name: 'Repository Sync Action'
description: 'Synchronize repositories'
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  source_repository_url_list:
    description: 'List of source repository URLs, one per line'
    required: true
  source_repository_username:
    description: 'Source repository username'
    required: false
  source_repository_password:
    description: 'Source repository password'
    required: false
  target_repository_url_list:
    description: 'List of target repository URLs, one per line'
    required: true
  target_repository_username:
    description: 'Target repository username'
    required: false
  target_repository_password:
    description: 'Target repository password'
    required: false

# Define your outputs here.
outputs:
  time:
    description: 'The time the action was run'

runs:
  using: 'node20'
  main: 'dist/index.js'
